create table if not exists assets
(
    id         bigint primary key generated by default as identity,
    issuer_id  bigint references entities(id) not null,
    name       text    not null,
    verified   boolean not null default false,
    unique (issuer_id, name),
    created_at timestamp with time zone default now()
);
