create table if not exists ticks (
    id bigint primary key generated by default as identity,
    tick_number bigint unique not null, -- indexed
    epoch bigint not null,
    created_at timestamp with time zone default now()
)