create table if not exists transactions (
    id bigint primary key generated by default as identity,
    hash text unique not null, -- indexed
    tick_id bigint references ticks(id) not null,
    created_at timestamp with time zone default now() not null
);

create index on transactions(tick_id);
