create table if not exists events (
    id bigint primary key generated by default as identity,
    transaction_id bigint references transactions(id) not null,
    event_id bigint not null, -- not sure if unique on its own
    event_type smallint not null,
    event_data text not null,
    created_at timestamp with time zone default now() not null,
    unique (transaction_id, event_id)
);

create index on events(transaction_id);
create index on events(event_type);
