create table if not exists events (
    id bigint primary key generated by default as identity,
    transaction_id bigint references transactions(id) not null,
    event_id bigint unique not null,
    event_type smallint not null,
    event_data text not null,
    created_at timestamp with time zone default now()
);

create index on events(transaction_id);
create index on events(event_type);
