create table if not exists qu_transfer_events (
    id bigint primary key generated by default as identity,
    event_id bigint references events(id) unique not null,
    source_entity_id bigint references entities(id) not null,
    destination_entity_id bigint references entities(id) not null,
    amount bigint not null
);

create index on qu_transfer_events(event_id);
create index on qu_transfer_events(source_entity_id);
create index on qu_transfer_events(destination_entity_id);
