create table if not exists key_values
(
    id bigint primary key generated by default as identity,
    key text unique not null,
    numeric_value bigint not null,
    updated_at timestamp with time zone default now() not null,
    created_at timestamp with time zone default now() not null
);

create trigger trigger_key_values_updated_at
    before update on key_values
    for each row execute procedure
    set_updated_at_time();
