-- doesn't make much sense, but we recreate the table to stay consistent
create table if not exists asset_issuance_events (
     id bigint primary key generated by default as identity,
     event_id bigint references events(id) unique not null,
     asset_id bigint references assets(id) not null,
     number_of_shares bigint not null,
     unit_of_measurement bytea not null,
     number_of_decimal_places smallint not null
);

create index on asset_change_events(event_id);
create index on asset_change_events(asset_id);