// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TransferServiceClient is the client API for TransferService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransferServiceClient interface {
	Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error)
	GetAssetChangeEventsForTick(ctx context.Context, in *TickRequest, opts ...grpc.CallOption) (*AssetChangeEventsResponse, error)
	GetQuTransferEventsForTick(ctx context.Context, in *TickRequest, opts ...grpc.CallOption) (*QuTransferEventsResponse, error)
	GetAssetChangeEventsForEntity(ctx context.Context, in *EntityRequest, opts ...grpc.CallOption) (*AssetChangeEventsResponse, error)
	GetQuTransferEventsForEntity(ctx context.Context, in *EntityRequest, opts ...grpc.CallOption) (*QuTransferEventsResponse, error)
}

type transferServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransferServiceClient(cc grpc.ClientConnInterface) TransferServiceClient {
	return &transferServiceClient{cc}
}

func (c *transferServiceClient) Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/qubic.transfers.proto.TransferService/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferServiceClient) GetAssetChangeEventsForTick(ctx context.Context, in *TickRequest, opts ...grpc.CallOption) (*AssetChangeEventsResponse, error) {
	out := new(AssetChangeEventsResponse)
	err := c.cc.Invoke(ctx, "/qubic.transfers.proto.TransferService/GetAssetChangeEventsForTick", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferServiceClient) GetQuTransferEventsForTick(ctx context.Context, in *TickRequest, opts ...grpc.CallOption) (*QuTransferEventsResponse, error) {
	out := new(QuTransferEventsResponse)
	err := c.cc.Invoke(ctx, "/qubic.transfers.proto.TransferService/GetQuTransferEventsForTick", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferServiceClient) GetAssetChangeEventsForEntity(ctx context.Context, in *EntityRequest, opts ...grpc.CallOption) (*AssetChangeEventsResponse, error) {
	out := new(AssetChangeEventsResponse)
	err := c.cc.Invoke(ctx, "/qubic.transfers.proto.TransferService/GetAssetChangeEventsForEntity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferServiceClient) GetQuTransferEventsForEntity(ctx context.Context, in *EntityRequest, opts ...grpc.CallOption) (*QuTransferEventsResponse, error) {
	out := new(QuTransferEventsResponse)
	err := c.cc.Invoke(ctx, "/qubic.transfers.proto.TransferService/GetQuTransferEventsForEntity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransferServiceServer is the server API for TransferService service.
// All implementations must embed UnimplementedTransferServiceServer
// for forward compatibility
type TransferServiceServer interface {
	Health(context.Context, *emptypb.Empty) (*HealthResponse, error)
	GetAssetChangeEventsForTick(context.Context, *TickRequest) (*AssetChangeEventsResponse, error)
	GetQuTransferEventsForTick(context.Context, *TickRequest) (*QuTransferEventsResponse, error)
	GetAssetChangeEventsForEntity(context.Context, *EntityRequest) (*AssetChangeEventsResponse, error)
	GetQuTransferEventsForEntity(context.Context, *EntityRequest) (*QuTransferEventsResponse, error)
	mustEmbedUnimplementedTransferServiceServer()
}

// UnimplementedTransferServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTransferServiceServer struct {
}

func (UnimplementedTransferServiceServer) Health(context.Context, *emptypb.Empty) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedTransferServiceServer) GetAssetChangeEventsForTick(context.Context, *TickRequest) (*AssetChangeEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssetChangeEventsForTick not implemented")
}
func (UnimplementedTransferServiceServer) GetQuTransferEventsForTick(context.Context, *TickRequest) (*QuTransferEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuTransferEventsForTick not implemented")
}
func (UnimplementedTransferServiceServer) GetAssetChangeEventsForEntity(context.Context, *EntityRequest) (*AssetChangeEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssetChangeEventsForEntity not implemented")
}
func (UnimplementedTransferServiceServer) GetQuTransferEventsForEntity(context.Context, *EntityRequest) (*QuTransferEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuTransferEventsForEntity not implemented")
}
func (UnimplementedTransferServiceServer) mustEmbedUnimplementedTransferServiceServer() {}

// UnsafeTransferServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransferServiceServer will
// result in compilation errors.
type UnsafeTransferServiceServer interface {
	mustEmbedUnimplementedTransferServiceServer()
}

func RegisterTransferServiceServer(s grpc.ServiceRegistrar, srv TransferServiceServer) {
	s.RegisterService(&TransferService_ServiceDesc, srv)
}

func _TransferService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qubic.transfers.proto.TransferService/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServiceServer).Health(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferService_GetAssetChangeEventsForTick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServiceServer).GetAssetChangeEventsForTick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qubic.transfers.proto.TransferService/GetAssetChangeEventsForTick",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServiceServer).GetAssetChangeEventsForTick(ctx, req.(*TickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferService_GetQuTransferEventsForTick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServiceServer).GetQuTransferEventsForTick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qubic.transfers.proto.TransferService/GetQuTransferEventsForTick",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServiceServer).GetQuTransferEventsForTick(ctx, req.(*TickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferService_GetAssetChangeEventsForEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServiceServer).GetAssetChangeEventsForEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qubic.transfers.proto.TransferService/GetAssetChangeEventsForEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServiceServer).GetAssetChangeEventsForEntity(ctx, req.(*EntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferService_GetQuTransferEventsForEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServiceServer).GetQuTransferEventsForEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qubic.transfers.proto.TransferService/GetQuTransferEventsForEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServiceServer).GetQuTransferEventsForEntity(ctx, req.(*EntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransferService_ServiceDesc is the grpc.ServiceDesc for TransferService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransferService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qubic.transfers.proto.TransferService",
	HandlerType: (*TransferServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _TransferService_Health_Handler,
		},
		{
			MethodName: "GetAssetChangeEventsForTick",
			Handler:    _TransferService_GetAssetChangeEventsForTick_Handler,
		},
		{
			MethodName: "GetQuTransferEventsForTick",
			Handler:    _TransferService_GetQuTransferEventsForTick_Handler,
		},
		{
			MethodName: "GetAssetChangeEventsForEntity",
			Handler:    _TransferService_GetAssetChangeEventsForEntity_Handler,
		},
		{
			MethodName: "GetQuTransferEventsForEntity",
			Handler:    _TransferService_GetQuTransferEventsForEntity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transfers.proto",
}
