// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: transfers.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Components    map[string]*Component  `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_transfers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_transfers_proto_rawDescGZIP(), []int{0}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetComponents() map[string]*Component {
	if x != nil {
		return x.Components
	}
	return nil
}

type Component struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Details       map[string]string      `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Component) Reset() {
	*x = Component{}
	mi := &file_transfers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Component) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Component) ProtoMessage() {}

func (x *Component) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Component.ProtoReflect.Descriptor instead.
func (*Component) Descriptor() ([]byte, []int) {
	return file_transfers_proto_rawDescGZIP(), []int{1}
}

func (x *Component) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Component) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type TickRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          uint32                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickRequest) Reset() {
	*x = TickRequest{}
	mi := &file_transfers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickRequest) ProtoMessage() {}

func (x *TickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickRequest.ProtoReflect.Descriptor instead.
func (*TickRequest) Descriptor() ([]byte, []int) {
	return file_transfers_proto_rawDescGZIP(), []int{2}
}

func (x *TickRequest) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

type EntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityRequest) Reset() {
	*x = EntityRequest{}
	mi := &file_transfers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityRequest) ProtoMessage() {}

func (x *EntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityRequest.ProtoReflect.Descriptor instead.
func (*EntityRequest) Descriptor() ([]byte, []int) {
	return file_transfers_proto_rawDescGZIP(), []int{3}
}

func (x *EntityRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type AssetChangeEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LatestTick    uint32                 `protobuf:"varint,1,opt,name=latestTick,proto3" json:"latestTick,omitempty"`
	Events        []*AssetChangeEvent    `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetChangeEventsResponse) Reset() {
	*x = AssetChangeEventsResponse{}
	mi := &file_transfers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetChangeEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetChangeEventsResponse) ProtoMessage() {}

func (x *AssetChangeEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetChangeEventsResponse.ProtoReflect.Descriptor instead.
func (*AssetChangeEventsResponse) Descriptor() ([]byte, []int) {
	return file_transfers_proto_rawDescGZIP(), []int{4}
}

func (x *AssetChangeEventsResponse) GetLatestTick() uint32 {
	if x != nil {
		return x.LatestTick
	}
	return 0
}

func (x *AssetChangeEventsResponse) GetEvents() []*AssetChangeEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type AssetEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LatestTick    uint32                 `protobuf:"varint,1,opt,name=latestTick,proto3" json:"latestTick,omitempty"`
	ChangeEvents  []*AssetChangeEvent    `protobuf:"bytes,2,rep,name=changeEvents,proto3" json:"changeEvents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetEventsResponse) Reset() {
	*x = AssetEventsResponse{}
	mi := &file_transfers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetEventsResponse) ProtoMessage() {}

func (x *AssetEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetEventsResponse.ProtoReflect.Descriptor instead.
func (*AssetEventsResponse) Descriptor() ([]byte, []int) {
	return file_transfers_proto_rawDescGZIP(), []int{5}
}

func (x *AssetEventsResponse) GetLatestTick() uint32 {
	if x != nil {
		return x.LatestTick
	}
	return 0
}

func (x *AssetEventsResponse) GetChangeEvents() []*AssetChangeEvent {
	if x != nil {
		return x.ChangeEvents
	}
	return nil
}

type QuTransferEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LatestTick    uint32                 `protobuf:"varint,1,opt,name=latestTick,proto3" json:"latestTick,omitempty"`
	Events        []*QuTransferEvent     `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuTransferEventsResponse) Reset() {
	*x = QuTransferEventsResponse{}
	mi := &file_transfers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuTransferEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuTransferEventsResponse) ProtoMessage() {}

func (x *QuTransferEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuTransferEventsResponse.ProtoReflect.Descriptor instead.
func (*QuTransferEventsResponse) Descriptor() ([]byte, []int) {
	return file_transfers_proto_rawDescGZIP(), []int{6}
}

func (x *QuTransferEventsResponse) GetLatestTick() uint32 {
	if x != nil {
		return x.LatestTick
	}
	return 0
}

func (x *QuTransferEventsResponse) GetEvents() []*QuTransferEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type QuTransferEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SourceId        string                 `protobuf:"bytes,1,opt,name=sourceId,proto3" json:"sourceId,omitempty"`
	DestinationId   string                 `protobuf:"bytes,2,opt,name=destinationId,proto3" json:"destinationId,omitempty"`
	Amount          uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	TransactionHash string                 `protobuf:"bytes,4,opt,name=transactionHash,proto3" json:"transactionHash,omitempty"`
	Tick            uint32                 `protobuf:"varint,5,opt,name=tick,proto3" json:"tick,omitempty"`
	EventType       uint32                 `protobuf:"varint,6,opt,name=eventType,proto3" json:"eventType,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QuTransferEvent) Reset() {
	*x = QuTransferEvent{}
	mi := &file_transfers_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuTransferEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuTransferEvent) ProtoMessage() {}

func (x *QuTransferEvent) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuTransferEvent.ProtoReflect.Descriptor instead.
func (*QuTransferEvent) Descriptor() ([]byte, []int) {
	return file_transfers_proto_rawDescGZIP(), []int{7}
}

func (x *QuTransferEvent) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *QuTransferEvent) GetDestinationId() string {
	if x != nil {
		return x.DestinationId
	}
	return ""
}

func (x *QuTransferEvent) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *QuTransferEvent) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

func (x *QuTransferEvent) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *QuTransferEvent) GetEventType() uint32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

type AssetChangeEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SourceId        string                 `protobuf:"bytes,1,opt,name=sourceId,proto3" json:"sourceId,omitempty"`
	DestinationId   string                 `protobuf:"bytes,2,opt,name=destinationId,proto3" json:"destinationId,omitempty"`
	IssuerId        string                 `protobuf:"bytes,3,opt,name=issuerId,proto3" json:"issuerId,omitempty"`
	Name            string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	NumberOfShares  uint64                 `protobuf:"varint,5,opt,name=numberOfShares,proto3" json:"numberOfShares,omitempty"`
	TransactionHash string                 `protobuf:"bytes,6,opt,name=transactionHash,proto3" json:"transactionHash,omitempty"`
	Tick            uint32                 `protobuf:"varint,7,opt,name=tick,proto3" json:"tick,omitempty"`
	EventType       uint32                 `protobuf:"varint,8,opt,name=eventType,proto3" json:"eventType,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AssetChangeEvent) Reset() {
	*x = AssetChangeEvent{}
	mi := &file_transfers_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetChangeEvent) ProtoMessage() {}

func (x *AssetChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetChangeEvent.ProtoReflect.Descriptor instead.
func (*AssetChangeEvent) Descriptor() ([]byte, []int) {
	return file_transfers_proto_rawDescGZIP(), []int{8}
}

func (x *AssetChangeEvent) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *AssetChangeEvent) GetDestinationId() string {
	if x != nil {
		return x.DestinationId
	}
	return ""
}

func (x *AssetChangeEvent) GetIssuerId() string {
	if x != nil {
		return x.IssuerId
	}
	return ""
}

func (x *AssetChangeEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AssetChangeEvent) GetNumberOfShares() uint64 {
	if x != nil {
		return x.NumberOfShares
	}
	return 0
}

func (x *AssetChangeEvent) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

func (x *AssetChangeEvent) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *AssetChangeEvent) GetEventType() uint32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

var File_transfers_proto protoreflect.FileDescriptor

const file_transfers_proto_rawDesc = "" +
	"\n" +
	"\x0ftransfers.proto\x12\x15qubic.transfers.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xe0\x01\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12U\n" +
	"\n" +
	"components\x18\x02 \x03(\v25.qubic.transfers.proto.HealthResponse.ComponentsEntryR\n" +
	"components\x1a_\n" +
	"\x0fComponentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .qubic.transfers.proto.ComponentR\x05value:\x028\x01\"\xa8\x01\n" +
	"\tComponent\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12G\n" +
	"\adetails\x18\x02 \x03(\v2-.qubic.transfers.proto.Component.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"!\n" +
	"\vTickRequest\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\rR\x04tick\"+\n" +
	"\rEntityRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\"|\n" +
	"\x19AssetChangeEventsResponse\x12\x1e\n" +
	"\n" +
	"latestTick\x18\x01 \x01(\rR\n" +
	"latestTick\x12?\n" +
	"\x06events\x18\x02 \x03(\v2'.qubic.transfers.proto.AssetChangeEventR\x06events\"\x82\x01\n" +
	"\x13AssetEventsResponse\x12\x1e\n" +
	"\n" +
	"latestTick\x18\x01 \x01(\rR\n" +
	"latestTick\x12K\n" +
	"\fchangeEvents\x18\x02 \x03(\v2'.qubic.transfers.proto.AssetChangeEventR\fchangeEvents\"z\n" +
	"\x18QuTransferEventsResponse\x12\x1e\n" +
	"\n" +
	"latestTick\x18\x01 \x01(\rR\n" +
	"latestTick\x12>\n" +
	"\x06events\x18\x02 \x03(\v2&.qubic.transfers.proto.QuTransferEventR\x06events\"\xc7\x01\n" +
	"\x0fQuTransferEvent\x12\x1a\n" +
	"\bsourceId\x18\x01 \x01(\tR\bsourceId\x12$\n" +
	"\rdestinationId\x18\x02 \x01(\tR\rdestinationId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\x12(\n" +
	"\x0ftransactionHash\x18\x04 \x01(\tR\x0ftransactionHash\x12\x12\n" +
	"\x04tick\x18\x05 \x01(\rR\x04tick\x12\x1c\n" +
	"\teventType\x18\x06 \x01(\rR\teventType\"\x88\x02\n" +
	"\x10AssetChangeEvent\x12\x1a\n" +
	"\bsourceId\x18\x01 \x01(\tR\bsourceId\x12$\n" +
	"\rdestinationId\x18\x02 \x01(\tR\rdestinationId\x12\x1a\n" +
	"\bissuerId\x18\x03 \x01(\tR\bissuerId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12&\n" +
	"\x0enumberOfShares\x18\x05 \x01(\x04R\x0enumberOfShares\x12(\n" +
	"\x0ftransactionHash\x18\x06 \x01(\tR\x0ftransactionHash\x12\x12\n" +
	"\x04tick\x18\a \x01(\rR\x04tick\x12\x1c\n" +
	"\teventType\x18\b \x01(\rR\teventType2\xc0\a\n" +
	"\x0fTransferService\x12_\n" +
	"\x06Health\x12\x16.google.protobuf.Empty\x1a%.qubic.transfers.proto.HealthResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/status/health\x12\x93\x01\n" +
	"\x15GetAssetEventsForTick\x12\".qubic.transfers.proto.TickRequest\x1a*.qubic.transfers.proto.AssetEventsResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/api/v1/ticks/{tick}/events/assets\x12\xa8\x01\n" +
	"\x1bGetAssetChangeEventsForTick\x12\".qubic.transfers.proto.TickRequest\x1a0.qubic.transfers.proto.AssetChangeEventsResponse\"3\x82\xd3\xe4\x93\x02-\x12+/api/v1/ticks/{tick}/events/asset-transfers\x12\xb3\x01\n" +
	"\x1dGetAssetChangeEventsForEntity\x12$.qubic.transfers.proto.EntityRequest\x1a0.qubic.transfers.proto.AssetChangeEventsResponse\":\x82\xd3\xe4\x93\x024\x122/api/v1/entities/{identity}/events/asset-transfers\x12\xa3\x01\n" +
	"\x1aGetQuTransferEventsForTick\x12\".qubic.transfers.proto.TickRequest\x1a/.qubic.transfers.proto.QuTransferEventsResponse\"0\x82\xd3\xe4\x93\x02*\x12(/api/v1/ticks/{tick}/events/qu-transfers\x12\xae\x01\n" +
	"\x1cGetQuTransferEventsForEntity\x12$.qubic.transfers.proto.EntityRequest\x1a/.qubic.transfers.proto.QuTransferEventsResponse\"7\x82\xd3\xe4\x93\x021\x12//api/v1/entities/{identity}/events/qu-transfersB&Z$github.com/qubic/go-transfers/proto/b\x06proto3"

var (
	file_transfers_proto_rawDescOnce sync.Once
	file_transfers_proto_rawDescData []byte
)

func file_transfers_proto_rawDescGZIP() []byte {
	file_transfers_proto_rawDescOnce.Do(func() {
		file_transfers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transfers_proto_rawDesc), len(file_transfers_proto_rawDesc)))
	})
	return file_transfers_proto_rawDescData
}

var file_transfers_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_transfers_proto_goTypes = []any{
	(*HealthResponse)(nil),            // 0: qubic.transfers.proto.HealthResponse
	(*Component)(nil),                 // 1: qubic.transfers.proto.Component
	(*TickRequest)(nil),               // 2: qubic.transfers.proto.TickRequest
	(*EntityRequest)(nil),             // 3: qubic.transfers.proto.EntityRequest
	(*AssetChangeEventsResponse)(nil), // 4: qubic.transfers.proto.AssetChangeEventsResponse
	(*AssetEventsResponse)(nil),       // 5: qubic.transfers.proto.AssetEventsResponse
	(*QuTransferEventsResponse)(nil),  // 6: qubic.transfers.proto.QuTransferEventsResponse
	(*QuTransferEvent)(nil),           // 7: qubic.transfers.proto.QuTransferEvent
	(*AssetChangeEvent)(nil),          // 8: qubic.transfers.proto.AssetChangeEvent
	nil,                               // 9: qubic.transfers.proto.HealthResponse.ComponentsEntry
	nil,                               // 10: qubic.transfers.proto.Component.DetailsEntry
	(*emptypb.Empty)(nil),             // 11: google.protobuf.Empty
}
var file_transfers_proto_depIdxs = []int32{
	9,  // 0: qubic.transfers.proto.HealthResponse.components:type_name -> qubic.transfers.proto.HealthResponse.ComponentsEntry
	10, // 1: qubic.transfers.proto.Component.details:type_name -> qubic.transfers.proto.Component.DetailsEntry
	8,  // 2: qubic.transfers.proto.AssetChangeEventsResponse.events:type_name -> qubic.transfers.proto.AssetChangeEvent
	8,  // 3: qubic.transfers.proto.AssetEventsResponse.changeEvents:type_name -> qubic.transfers.proto.AssetChangeEvent
	7,  // 4: qubic.transfers.proto.QuTransferEventsResponse.events:type_name -> qubic.transfers.proto.QuTransferEvent
	1,  // 5: qubic.transfers.proto.HealthResponse.ComponentsEntry.value:type_name -> qubic.transfers.proto.Component
	11, // 6: qubic.transfers.proto.TransferService.Health:input_type -> google.protobuf.Empty
	2,  // 7: qubic.transfers.proto.TransferService.GetAssetEventsForTick:input_type -> qubic.transfers.proto.TickRequest
	2,  // 8: qubic.transfers.proto.TransferService.GetAssetChangeEventsForTick:input_type -> qubic.transfers.proto.TickRequest
	3,  // 9: qubic.transfers.proto.TransferService.GetAssetChangeEventsForEntity:input_type -> qubic.transfers.proto.EntityRequest
	2,  // 10: qubic.transfers.proto.TransferService.GetQuTransferEventsForTick:input_type -> qubic.transfers.proto.TickRequest
	3,  // 11: qubic.transfers.proto.TransferService.GetQuTransferEventsForEntity:input_type -> qubic.transfers.proto.EntityRequest
	0,  // 12: qubic.transfers.proto.TransferService.Health:output_type -> qubic.transfers.proto.HealthResponse
	5,  // 13: qubic.transfers.proto.TransferService.GetAssetEventsForTick:output_type -> qubic.transfers.proto.AssetEventsResponse
	4,  // 14: qubic.transfers.proto.TransferService.GetAssetChangeEventsForTick:output_type -> qubic.transfers.proto.AssetChangeEventsResponse
	4,  // 15: qubic.transfers.proto.TransferService.GetAssetChangeEventsForEntity:output_type -> qubic.transfers.proto.AssetChangeEventsResponse
	6,  // 16: qubic.transfers.proto.TransferService.GetQuTransferEventsForTick:output_type -> qubic.transfers.proto.QuTransferEventsResponse
	6,  // 17: qubic.transfers.proto.TransferService.GetQuTransferEventsForEntity:output_type -> qubic.transfers.proto.QuTransferEventsResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_transfers_proto_init() }
func file_transfers_proto_init() {
	if File_transfers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transfers_proto_rawDesc), len(file_transfers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transfers_proto_goTypes,
		DependencyIndexes: file_transfers_proto_depIdxs,
		MessageInfos:      file_transfers_proto_msgTypes,
	}.Build()
	File_transfers_proto = out.File
	file_transfers_proto_goTypes = nil
	file_transfers_proto_depIdxs = nil
}
